# SETTINGS FOR MEG REPLAY TASK
arrow positions:
  arrow_gap: 3  # Gap between arrow stimuli
number training trials:
  n_training_trials: 40  # Number of trials in the training session
  n_test_trials: 20  # Number of trials in the test session
  n_test_successes: 5  # Number of consecutive successes required to pass the test phase
durations:
  start_duration: 5  #
  pre_move_duration: 3  #
  move_entering_duration: 3  # Time given to enter moves
  move_durations: 2  # Time each move is shown for
  outcome_only_text_duration: 2  #
  outcome_only_duration: 3  #
  rest_duration: 3  # Rest after outcome
  shock_delay: 0.5  # Delay before shocks are given following the shock image
  n_moves: 3  # Number of moves subjects make
  n_shocks: 5  # Number of shocks in each shock train
directories:
  saved_data: 'Data/behavioural/pilot'
  stimuli_path: 'Stimuli'
  arrow_path: 'Stimuli/Arrows'
  matrix: 'Task_information/transition_matrix.txt'
  trial_info: 'Task_information/trial_info.csv'
  trial_info_test: 'Task_information/trial_info_test.csv'
  main_instructions: 'Instructions/instructions.txt'
  training_instructions: 'Instructions/training_instructions.txt'
  task_instructions: 'Instructions/task_instructions.txt'
  test_instructions: 'Instructions/test_instructions.txt'
filenames:
  save_prefix: 'replay_task_behavioural'
response keys:
  response_keys: ['down', 'left', 'right', 'up']
image sizes:
  size_image_size: !!python/tuple [6, 6]  # Size of the state image stimuli
  size_outcome_image: !!python/tuple [2, 3]  #
  size_display_image: !!python/tuple [11, 11]  #
  size_arrow_display: !!python/tuple [2, 3]  # Size of the arrow stimuli
fonts:
  font_path: 'fonts/OpenSans-Regular.ttf'
  font_name: 'Open Sans'


