durations:
  image_duration: 1.4  #
  image_jitter: 0.5  #
  fixation_duration: 1  #
  fixation_jitter: 0.5  #
  text_duration: 1.2  #
  text_jitter: 0.3  #
task_settings:
  n_trials: 150
  n_stimuli: 7
  n_blocks: 6
  percentage_faded: 30
  percentage_null: 7
image_sizes:
  size_display_image: !!python/tuple [11, 11]  #
  size_display_image_small: !!python/tuple [10.5, 10.5]  #
  test_alpha: 0.7
directories:
  stimuli_path: '../Task/Stimuli'
  saved_data: 'Data/'
filenames:
  save_prefix: 'replay_task_behavioural'
